//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Lucifer.rc
//
#define IDR_MANIFEST                    1
#define IDD_USB2DEV_DIALOG              102
#define IDI_CAMERA                      120
#define IDD_CHOOSE_DEVICE               120
#define IDI_CONTRAST                    121
#define IDI_BRIGHTNESS                  122
#define IDD_ABOUT                       132
#define IDD_MAIN_DIALOG                 138
#define IDI_ICON1                       139
#define IDI_LUCI                        139
#define IDD_CLK_TIMING_TAB              140
#define IDD_AUTOFOCUS_REVIEW            141
#define IDR_BUSY                        142
#define IDD_GENERAL_TAB                 143
#define IDD_CLK_TAB                     144
#define IDD_POWER_TAB                   145
#define IDD_SETTINGS                    146
#define IDD_ASP_TAB                     150
#define IDC_SCOPE                       1000
#define IDC_SCAN                        1001
#define IDC_SNAP                        1001
#define IDC_CONTROLS                    1002
#define IDC_EDIT_SETTINGS               1002
#define IDC_SCAN_LINES                  1005
#define IDC_NAME                        1008
#define IDC_LINE_COUNT                  1009
#define IDC_FIRMWARE                    1010
#define IDC_VPELTIER_SLIDER             1010
#define IDC_MAXSWEEP                    1011
#define IDC_MULT_GAIN                   1011
#define IDC_MAXRATE                     1012
#define IDC_MASTERVER                   1012
#define IDC_ANALOG_GAIN                 1012
#define IDC_EEPROM_BYTES                1012
#define IDC_SERIAL                      1013
#define IDC_ANALOG_LEVEL                1013
#define IDC_EEPROM_DATA                 1013
#define IDC_MINRATE                     1014
#define IDC_VERSION                     1014
#define IDC_EEPROM_READ                 1014
#define IDC_MSG                         1015
#define IDC_LIST                        1015
#define IDC_WAITMSG                     1015
#define IDC_EEPROM_WRITE                1015
#define IDC_ANIMATION                   1016
#define IDC_WAIT_MSG                    1016
#define IDC_BULK_BYTES                  1016
#define IDC_TABCONTROL                  1016
#define IDC_ABOUT                       1017
#define IDC_BULK_DATA                   1017
#define IDC_COPY                        1018
#define IDC_BULK_READ                   1018
#define IDC_AUTOYSCALE                  1019
#define IDC_BRIGHTNESS                  1019
#define IDC_BRIGHTNESS_TITLE            1020
#define IDC_VR_BYTES                    1020
#define IDC_PRODUCT                     1021
#define IDC_CONTRAST                    1021
#define IDC_VR_DATA                     1021
#define IDC_DRIVER                      1022
#define IDC_CONTRAST_TITLE              1022
#define IDC_VR_READ                     1022
#define IDC_APP                         1023
#define IDC_VR_WRITE                    1023
#define IDC_VR_REQUEST                  1024
#define IDC_BINX                        1024
#define IDC_PERSISTANCE                 1025
#define IDC_VR_VALUE                    1025
#define IDC_ASP1                        1025
#define IDC_CLEAR                       1026
#define IDC_VR_INDEX                    1026
#define IDC_ASP2                        1026
#define IDC_RATE                        1027
#define IDC_VR_TIMEOUT                  1027
#define IDC_ASP3                        1027
#define IDC_ASP4                        1028
#define IDC_STOP                        1029
#define IDC_INFO                        1029
#define IDC_EXPOSURE_MS                 1030
#define IDC_VPELTIER_SLIDER_VALUE       1031
#define IDC_MUL_GAIN                    1031
#define IDC_DELAYMS                     1031
#define IDC_MULT_GAIN_VALUE             1032
#define IDC_EEPROM_START                1032
#define IDC_USBDEV                      1032
#define IDC_LOOPS                       1032
#define IDC_ANALOG_GAIN_VALUE           1033
#define IDC_DOWNLOAD_EEPROM             1033
#define IDC_ANALOG_LEVEL_VALUE          1034
#define IDC_RESET                       1034
#define IDC_ERROR                       1035
#define IDC_EDIT1                       1036
#define IDC_PROGRESS                    1037
#define IDC_BIAS_ON                     1037
#define IDC_BINY                        1037
#define IDC_CLOCK_TEMPERATURE           1038
#define IDC_ASP_TEMPERATURE             1039
#define IDC_SPINNER_EXPOSURE            1040
#define IDC_SAVE_TIFF                   1041
#define IDC_SPINNER_DELAYMS             1041
#define IDC_SPINNER_LOOPS               1042
#define IDC_GAIN_X1                     1043
#define IDC_GAIN_X4                     1044
#define IDC_RESET_BLANK                 1045
#define IDC_SAVE_RAW                    1046
#define IDC_SPINNER_ADCREADS            1046
#define IDC_VIDEO                       1047
#define IDC_CHANNEL                     1048
#define IDC_JJ                          1048
#define IDC_FLIPY                       1048
#define IDC_CURSORPOS                   1049
#define IDC_SPINNER_JJ                  1049
#define IDC_ADJ1                        1050
#define IDC_IMAGESIZE                   1050
#define IDC_MODEPARAMS                  1050
#define IDC_SPINNER_ADJ1                1051
#define IDC_2BYTE                       1052
#define IDC_LOAD                        1052
#define IDC_MON_ADJ1                    1052
#define IDC_DEVICE_CONTROL              1053
#define IDC_SAVE                        1053
#define IDC_ADJ2                        1053
#define IDC_XMIN1                       1053
#define IDC_SPINNER_ADJ2                1054
#define IDC_SPINNER_XMIN1               1054
#define IDC_DEVICE_RESET                1055
#define IDC_INITIALIZE                  1055
#define IDC_MON_ADJ2                    1055
#define IDC_XMAX1                       1055
#define IDC_ADJ3                        1056
#define IDC_SPINNER_XMAX1               1056
#define IDC_YMIN1                       1057
#define IDC_SPINNER_ADJ3                1057
#define IDC_MON_ADJ3                    1058
#define IDC_SPINNER_YMIN1               1058
#define IDC_ADJ4                        1059
#define IDC_YMAX1                       1059
#define IDC_SPINNER_ADJ4                1060
#define IDC_SPINNER_YMAX1               1060
#define IDC_MON_ADJ4                    1061
#define IDC_XMIN2                       1061
#define IDC_SPINNER_XMIN2               1062
#define IDC_XMAX2                       1063
#define IDC_SPINNER_XMAX2               1064
#define IDC_YMIN2                       1065
#define IDC_SPINNER_YMIN2               1066
#define IDC_YMAX2                       1067
#define IDC_SPINNER_YMAX2               1068
#define IDC_XMIN3                       1069
#define IDC_SPINNER_XMIN3               1070
#define IDC_XMAX3                       1071
#define IDC_SPINNER_XMAX3               1072
#define IDC_YMIN3                       1073
#define IDC_SPINNER_YMIN3               1074
#define IDC_YMAX3                       1075
#define IDC_SPINNER_YMAX3               1076
#define IDC_S13H                        1077
#define IDC_ROI2                        1077
#define IDC_P12H                        1078
#define IDC_TS1                         1078
#define IDC_ROI3                        1078
#define IDC_P3H                         1079
#define IDC_SPINNER_TS1                 1079
#define IDC_ROI1                        1079
#define IDC_RGH                         1080
#define IDC_TS2                         1080
#define IDC_TDI                         1080
#define IDC_TGH                         1081
#define IDC_SPINNER_TS2                 1081
#define IDC_PRESCAN                     1081
#define IDC_SGH                         1082
#define IDC_TS3                         1082
#define IDC_SPINNER_PRESCAN             1082
#define IDC_VOD                         1083
#define IDC_SPINNER_TS3                 1083
#define IDC_RMODE                       1083
#define IDC_VOG                         1084
#define IDC_TS4                         1084
#define IDC_SPINNER_TS4                 1085
#define IDC_TS5                         1086
#define IDC_RATE_SPINNER                1087
#define IDC_BRIGHTNESS_VALUE            1087
#define IDC_SPINNER_TS5                 1087
#define IDC_CONTRAST_VALUE              1088
#define IDC_TS6                         1088
#define IDC_SPINNER_TS6                 1089
#define IDC_TS7                         1090
#define IDC_SPINNER_TS7                 1091
#define IDC_TADC                        1092
#define IDC_SPINNER_TADC                1093
#define IDC_TSG                         1094
#define IDC_SPINNER_TSG                 1095
#define IDC_SPINNER_BINX                1095
#define IDC_CHANNEL_SPINNER             1096
#define IDC_TP1                         1096
#define IDC_SPINNER_TP1                 1097
#define IDC_SPINNER_BINY                1097
#define IDC_TP2                         1098
#define IDC_SPINNER_TP2                 1099
#define IDC_TP3                         1100
#define IDC_SPINNER_TP3                 1101
#define IDC_TP4                         1102
#define IDC_SPINNER_TP4                 1103
#define IDC_SPINNER_S13L                1103
#define IDC_TP5                         1104
#define IDC_SPINNER_P12L                1104
#define IDC_SPINNER_TP5                 1105
#define IDC_SPINNER_S13H                1105
#define IDC_TP6                         1106
#define IDC_SPINNER_P12H                1106
#define IDC_SPINNER_TP6                 1107
#define IDC_SPINNER_P3H                 1107
#define IDC_TP7                         1108
#define IDC_SPINNER_P3L                 1108
#define IDC_SPINNER_TP7                 1109
#define IDC_SPINNER_RGH                 1109
#define IDC_TMPP                        1110
#define IDC_SPINNER_RGL                 1110
#define IDC_SPINNER_TMPP                1111
#define IDC_SPINNER_TGH                 1111
#define IDC_SERIAL_TIMING               1112
#define IDC_SPINNER_TGL                 1112
#define IDC_S13L                        1113
#define IDC_TTDI                        1113
#define IDC_P12L                        1114
#define IDC_SPINNER_TTDI                1114
#define IDC_P3L                         1115
#define IDC_EXPOSURE                    1115
#define IDC_RGL                         1116
#define IDC_SERIAL_TIMING2              1116
#define IDC_MON_P5V                     1116
#define IDC_MON_M5V                     1117
#define IDC_ADCREADS                    1117
#define IDC_MON_P3V                     1118
#define IDC_ASPNUM                      1118
#define IDC_MON_P12V                    1119
#define IDC_CLKNUM                      1119
#define IDC_MON_M12V                    1120
#define IDC_FLUSH_NONE                  1120
#define IDC_MON_P28V                    1121
#define IDC_FLUSH                       1121
#define IDC_RELOAD                      1122
#define IDC_ASP_SET_BN                  1123
#define IDC_MON_P5A                     1124
#define IDC_ASP_GET_BN                  1124
#define IDC_TGL                         1125
#define IDC_MON_M5A                     1125
#define IDC_MON_P3A                     1126
#define IDC_CLK_GET_BN                  1126
#define IDC_MON_P12A                    1127
#define IDC_POLL_ASP                    1127
#define IDC_CLK_GET_BN2                 1127
#define IDC_CLK_SET_BN                  1127
#define IDC_SPINNER_SGH                 1128
#define IDC_MON_M12A                    1128
#define IDC_SGL                         1129
#define IDC_MON_P28A                    1129
#define IDC_SPINNER_SGL                 1130
#define IDC_SPINNER_RMODE               1131
#define IDC_POLL_CLK                    1131
#define IDC_SPINNER_ASPNUM              1132
#define IDC_SPINNER_VOD                 1133
#define IDC_VRD                         1134
#define IDC_SPINNER_VRD                 1135
#define IDC_MON_VOD                     1136
#define IDC_SPINNER_VOG                 1138
#define IDC_VDD                         1139
#define IDC_SPINNER_VDD                 1140
#define IDC_MON_VRD                     1143
#define IDC_AUTOSAVE                    1143
#define IDC_AUTOSAVE_PATH               1144
#define IDC_MON_VOG                     1144
#define IDC_SETPATH                     1145
#define IDC_MON_VDD                     1145
#define IDC_MON_S13H                    1148
#define IDC_MON_S13L                    1149
#define IDC_MON_P12H                    1150
#define IDC_MON_P12L                    1151
#define IDC_MON_RGH                     1152
#define IDC_MON_RGL                     1153
#define IDC_MON_TGH                     1154
#define IDC_MON_TGL                     1155
#define IDC_MON_SGH                     1156
#define IDC_MON_SGL                     1157
#define IDC_SPINNER_CLKNUM              1159
#define IDC_MON_P3H                     1160
#define IDC_MON_P3L                     1161
#define IDC_SENSOR_VALUE                1185
#define IDC_TEMPERATURE                 1185
#define IDC_POLLING                     1186
#define IDC_IMAGE                       2274

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1132
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
