FamilyName=CoolRunner2
VendorName=Xilinx
SynthArchName=coolrunner2
LogFileName=C:\Documents and Settings\rlobdill\My Documents\Altium Briefcase\Altum Projects\0.4 Lambert\ProjectOutputs\PWM generator\PWM_generator_Synth.log
OutputFileName=C:\Documents and Settings\rlobdill\My Documents\Altium Briefcase\Altum Projects\0.4 Lambert\ProjectOutputs\PWM generator\PWM_generator.edf
BFLFileName=C:\Documents and Settings\rlobdill\My Documents\Altium Briefcase\Altum Projects\0.4 Lambert\ProjectOutputs\PWM generator\PWM_generator.bfl
Entity=PWM_generator
VerilogMode=1
VHDL87=0
InsertIOBuffers=True
SDB_MaxMultipliers=0
InferRam=Block
SDB_ActiveLowAsynPreset=False
SDB_ActiveLowAsynReset=False
SDB_ActiveLowTristate=True
SDB_AlteraAdder=False
SDB_AlteraLpmAddSub=False
SDB_AlteraLpmCompare=False
SDB_AlteraLpmMultiply=False
SDB_AlteraMult=False
SDB_EnableAsynFlipFlop=False
SDB_EnableLatch=True
SDB_EnableSyncFlipFlop=False
SDB_LatticeCCU2=False
SDB_LatticeCCU2B=False
SDB_LatticeFADD2=False
SDB_LatticeFADD2B=False
SDB_LatticeFSUB2=False
SDB_LatticeFSUB2B=False
SDB_LatticeMult=False
SDB_TristatePushToTop=False
SDB_TristateToMux=False
SDB_XilinxMacroAdder=False
SDB_XilinxMacroMux=False
SDB_XilinxMult=False
SDB_XilinxMuxF56=False
SDB_XilinxMuxF78=False
