FamilyName=CoolRunnerXPLA3
VendorName=Xilinx
SynthArchName=coolrunnerXPLA3
LogFileName=\\Files\users\rlobdill\Altum Projects\0.4 Lambert\ProjectOutputs\Lambert_CPLD\Point4_Lambert_PLD_Project.synthlog
OutputFileName=\\Files\users\rlobdill\Altum Projects\0.4 Lambert\ProjectOutputs\Lambert_CPLD\Point4_Lambert_PLD_Project.edf
BFLFileName=\\Files\users\rlobdill\Altum Projects\0.4 Lambert\ProjectOutputs\Lambert_CPLD\Point4_Lambert_PLD_Project.bfl
Entity=Point4_Lambert_PLD_Project
VerilogMode=1
VHDL87=0
InsertIOBuffers=True
SDB_MaxMultipliers=0
InferRam=Auto
RomStyle=Logic
SisOptimizationLevel=Medium
SDB_ActiveLowAsynPreset=False
SDB_ActiveLowAsynReset=False
SDB_ActiveLowTristate=True
SDB_AlteraAdder=False
SDB_AlteraLpmAddSub=False
SDB_AlteraLpmCompare=False
SDB_AlteraLpmMultiply=False
SDB_AlteraLVDS=False
SDB_EdifBitvecInHex=True
SDB_EnableAsynFlipFlop=False
SDB_EnableLatch=True
SDB_EnableSyncFlipFlop=False
SDB_LatticeCCU2=False
SDB_LatticeCCU2B=False
SDB_LatticeFADD2=False
SDB_LatticeFADD2B=False
SDB_LatticeFSUB2=False
SDB_LatticeFSUB2B=False
SDB_LatticeMult=False
SDB_LatticeMultB=False
SDB_TristateInternalToMux=False
SDB_TristatePushToTop=False
SDB_TristateToMux=False
SDB_XilinxMacroAdder=False
SDB_XilinxMacroMux=False
SDB_XilinxMult=False
SDB_XilinxMuxF56=False
SDB_XilinxMuxF78=False
